eureka:
  client:
    serviceUrl:
      defaultZone: http://10.111.58.121:10000/eureka/
    enabled: false
server:
  tomcat:
    uri-encoding: UTF-8
  port: 11001
  context-path: /fasttiff
spring:
  application:
    name: fasttiff
