eureka:
  client:
    serviceUrl:
      defaultZone: http://10.111.8.181:8282/eureka/
server:
  tomcat:
    uri-encoding: UTF-8
  port: 11001
  context-path: /fasttiff
spring:
  application:
    name: fasttiff